version: '3.8'

services:
  tech_task_backend:
    container_name: tech_task
    image: tech_task:1.0.6
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
      - PGHOST
    depends_on:
      - tech_task_node_db
  tech_task_node_db:
    container_name: tech_task_node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}